name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.12.1'
      - uses: actions/checkout@v2
      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-artifacts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-artifacts-
          path: |
            ./_build
            ./deps
      - name: Fetch Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

  code-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.12.1'
      - uses: actions/checkout@v2
      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-artifacts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-artifacts-
          path: |
            ./_build
            ./deps
      - name: Cache PLTs
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-plts-
          path: ./priv/plts
      - name: Check Format
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
      - name: Run Dialyzer
        run: mix dialyzer
      - name: Run Sobelow
        run: mix sobelow

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      database:
        image: postgres:13.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.12.1'
      - uses: actions/checkout@v2
      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-artifacts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-artifacts-
          path: |
            ./_build
            ./deps
      - name: Cache Test Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-test-artifacts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-test-artifacts
          path: ./_build/test
      - name: Run Tests
        run: mix test --warnings-as-errors --cover





